import type { Metadata } from 'next';
import './globals.css';
import ThemeRegistryProvider from '../providers/ThemeRegistryProvider';
import { Navbar } from '@/components/Navbar';
import { GsapProvider } from '@/providers/GsapProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistryProvider>
          <GsapProvider>
            <Navbar />
            {children}
          </GsapProvider>
        </ThemeRegistryProvider>
      </body>
    </html>
  );
}
