import type { Metadata } from 'next';
import './globals.css';
import ThemeRegistryProvider from '../providers/ThemeRegistryProvider';
import Loader from '@/components/Loader/Loader';
import { Navbar } from '@/components/Navbar';
import { GsapProvider } from '@/providers/GsapProvider';
import { VisibilityProvider } from '@/providers/Testing';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <VisibilityProvider>
          <Loader />
          <ThemeRegistryProvider>
            <GsapProvider>
              <Navbar />
              {children}
            </GsapProvider>
          </ThemeRegistryProvider>
        </VisibilityProvider>
      </body>
    </html>
  );
}
